@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Feb 04 17:20:03 +0800 2024
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim testfixture_behav -key {Behavioral:sim_1:Functional:testfixture} -tclbatch testfixture.tcl -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Parallel_Vivado/testfixture_behav.wcfg -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Parallel_Vivado/CalCost.wcfg -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Heir_Vivado/LX_Sort.wcfg -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Heir_Vivado/JAM.wcfg -log simulate.log"
call xsim  testfixture_behav -key {Behavioral:sim_1:Functional:testfixture} -tclbatch testfixture.tcl -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Parallel_Vivado/testfixture_behav.wcfg -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Parallel_Vivado/CalCost.wcfg -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Heir_Vivado/LX_Sort.wcfg -view E:/Projects 專案/IC 競賽/110_IC_Contest_Preround/Verilog/JAM_Heir_Vivado/JAM.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
